#!/bin/sh
SERVICE_NAME=ATClient
PID_PATH_NAME=/tmp/ATClient-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -Dlog.file=/home/pi/atclient/atclient.log -Dlog4j.configurationFile=/home/pi/atclient/log4j2.xml -cp "/home/pi/atclient/class:/home/pi/atclient/lib/*" com.swisscom.atclient.GsmClient 2>> /dev/null >> /dev/null &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -Dlog.file=/home/pi/atclient/atclient.log -Dlog4j.configurationFile=/home/pi/atclient/log4j2.xml -cp "/home/pi/atclient/class:/home/pi/atclient/lib/*" com.swisscom.atclient.GsmClient 2>> /dev/null >> /dev/null &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 